version: 2.1

orbs:
  maven: circleci/maven@1.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: test
          command: ./mvnw test
      - run:
          name: package
          command: ./mvnw  package -DskipTests

  
